# Generated by Django 5.2.9 on 2026-02-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
