# Generated by Django 6.0 on 2025-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place_name',
            field=models.CharField(default='Unknown Location', max_length=200),
            preserve_default=False,
        ),
    ]
