# Generated by Django 6.0 on 2025-12-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_cancel_message_event_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cancel_message',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
