# Generated by Django 6.0 on 2025-12-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_cancel_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_qr',
        ),
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
