# Generated by Django 6.0 on 2025-12-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventregistration_payment_qr_event_payment_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='payment_qr',
        ),
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID for payment (paid events only)', max_length=100, null=True),
        ),
    ]
