# Generated by Django 5.2.9 on 2025-12-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='upi_id',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='CREATED', max_length=20),
        ),
    ]
